#!/bin/bash
#
# Prepares the "stack" to run apps and the environment to run buildpacks
#

#
# SYSTEM PACKAGES
#
apt-get update

# Get version of mysql library needed for HHVM
apt-get install -y --force-yes wget
wget -P /tmp http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.1/mysql-common_5.1.69-0ubuntu0.11.10.1_all.deb
wget -P /tmp http://security.ubuntu.com/ubuntu/pool/main/m/mysql-5.1/libmysqlclient16_5.1.69-0ubuntu0.11.10.1_amd64.deb
dpkg -i /tmp/mysql-common_5.1.69-0ubuntu0.11.10.1_all.deb
dpkg -i /tmp/libmysqlclient16_5.1.69-0ubuntu0.11.10.1_amd64.deb
rm -f /tmp/*.deb

xargs apt-get install -y --force-yes < /build/packages.txt
apt-get clean

#
# SUPPORTED BUILDPACKS
#
mkdir -p /build/buildpacks
cd /build/buildpacks
xargs -L 1 git clone --depth=1 < /build/buildpacks.txt

#
# MISC
#

# Ruby buildpack system configuration
update-alternatives --set ruby /usr/bin/ruby1.9.1
update-alternatives --set gem /usr/bin/gem1.9.1
gem install bundler --no-ri --no-rdoc
